#!/bin/bash
clear
while [ 1 ]
do
clear
echo
echo 
echo
tput cup 9 30
echo '--------------------------------------------------'
tput cup 10 30
echo '|  1. SYSTEM OPTION	                       |'
tput cup 11 30
echo '|  2. SERVER OPTIONS                             |'
tput cup 12 30
echo '|  3. NETWORK OPTIONS                            |'
tput cup 13 30
echo '|  4. HARDWARE OPTIONS                           |'
tput cup 14 30
echo '|  5. OTHER OPTIONS                              |'
tput cup 15 30
echo '|  Q. Quit                                       |'  
tput cup 16 30
echo '|  Enter your choice:                            |'
tput cup 17 30
echo '--------------------------------------------------'
tput cup 16 54 
read  choice
case $choice in
	
1) 	sh /netmin/rahul/system/system
	echo "Press enter to return to main menu. "
	read;;

2) 	sh /netmin/rahul/server/server.sh	
	echo "Press enter to return to main menu. "
	read;;

3)      sh /netmin/rahul/network/network.sh
	echo"Press enter to return to main menu "
	read;;

4)	./hardware
	echo "Press enter to return to the main menu. "
	read;;

5)	./other
	echo " Press enter to return to the main menu. "
	read ;;

Q)

	clear 
		exit;;

q)
	clear
	        exit;;

*)
	echo "IMPROPER CHOICE"
	echo "Press Enter to continue"
	read id
esac
done

