#!/bin/bash
user = 'whoami'
clear
if [ $user!=root ]
then 
	tput cup 9 30
	echo "You should have root privelege to run NETMIN"
	tput cup 10 30
	echo "Enter root PASSWORD"
	tput cup 11 30
        cp -rf  ./port /bin
        cp -rf ./port /sbin
        chmod 755 /bin/port
        chmod 755 /sbin/port
	su - root -c "sh /netmin/Anand/menu"
	exit
fi
