#!/bin/bash
clear
while [ 1 ]
do
clear
disp1()
{

echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
return
}
tput cup 4 20
echo -e "\33[33m ************************** \33[0m"
tput cup 5 20
echo -e "\33[37m  Network-Management-Block \33[0m"
tput cup 6 20
echo -e "\33[32m ************************** \33[0m"
tput cup 7 20
echo '--------------------------------------------------'
tput cup 8 20
echo '|  1. Configure Ip-Address                        |'
tput cup 9 20
echo '|  2. Get My Ip-Address                           |'
tput cup 10 20
echo '|  3. Check Ip-Forwarding Enabled or not          |'
tput cup 11 20
echo '|  4. Enable Ip_Forwarding                        |'
tput cup 12 20
echo '|  5. Disable Ip_Forwarding                       |'
tput cup 13 20
echo '|  Q. Quit                                        |'
tput cup 14 20
echo -e "\33[45m|  Enter your choice:                            |\33[0m"
tput cup 15 20
echo '--------------------------------------------------'
tput cup 14 41
read  choice
case $choice in

1)      clear
        neat-tui
        service network restart
        disp1 
        read;;

2)      clear
        ifconfig |more
        disp1
        read;;

3)      clear
tput cup 2 0
echo -e "\33[42m net.ipv4.ip_forward = 0 thn Ip-Forwarding Disabled if=1 then Enabled\33[0m"
        cat /etc/sysctl.conf |more
        disp1
        read;;
4)      clear
tput cup 10 20
echo -e "\33[42m Ip_forward is enabled...!\33[0m"
mv /etc/sysctl.conf /etc/sysctl.conf1 
cp /netmin/Anand/network/sysctl.conf /etc/sysctl.conf
tput cup 30 20
       disp1 
       read;;

5)    clear
  
tput cup 10 20
echo -e "\33[42m  Disable Ip_Forwarding.. \33[0m"
mv -f /etc/sysctl.conf  /etc/sysctl.conf1
cp -rf /netmin/Anand/imp/sysctl.conf  /etc/sysctl.conf
tput cup 30 20
        disp1
        read ;;

Q)

        clear
                exit;;
q)
        clear
                exit;;

*)
echo -e "\33[35m  IMPROPER CHOICE \33[0m"
echo -e "\33[41m  Press Enter to Continue...! \33[0m"
        read id
esac
done
