#!/bin/bash
clear
echo "Enter the name of the user" 
read name
echo "Enter the new primary group"
read gpname 
grep $gpname /etc/group 
if [ $? -ne 0 ] 
then 
echo "Group does not exist"
exit 
fi 
sed -n "/$name/s/$old/$new/4" /etc/passwd 
