#!/bin/bash
clear
tput cup 10 20
printf "Name the user whose password is to be changed: "
read user
if `grep -w $user /etc/passwd >>/dev/null`
then
tput cup 11 20
echo -n "Enter the password : "
stty -echo
read pass
stty sane
tput cup 12 20
echo $pass | passwd --stdin $user
stty sane
tput cup 16 20
echo "User $user 's password successfully changed"
else
tput cup 29 20
echo "User $user not exist"
fi
read;
