#!/bin/bash
clear
while [ 1 ]
do
clear
tput cup 4 20
echo -e "\33[33m ************************** \33[0m"
tput cup 5 20
echo -e "\33[37m  Welcome to Netmin Project \33[0m"
tput cup 6 20
echo -e "\33[32m ************************** \33[0m"
tput cup 9 20
echo '--------------------------------------------------'
tput cup 10 20
echo '|  1. Create Users                               |'
tput cup 11 20
echo '|  2. Create Groups                              |'
tput cup 12 20
echo '|  3. Modify User                                |'
tput cup 13 20
echo '|  4. Change Password                            |'
tput cup 14 20
echo '|  Q. Quit                                       |'  
tput cup 15 20
echo -e "\33[45m  Enter your choice:                             \33[0m"
tput cup 16 20
echo '--------------------------------------------------'
tput cup 15 40 
read  choice
case $choice in
	
1) 	sh /netmin/Anand/system/user
	tput cup 30 30
	echo "Press enter to return to main menu. "
	read;;

2) 	sh /netmin/Anand/system/groups
	tput cup 30 30
	echo "Press enter to return to main menu. "
	read;;

3)      sh /netmin/Anand/system/moduser
        tput cup 30 30
        echo "Press enter to return to main menu. "
        read;;


4)      sh /netmin/Anand/system/chpass
        tput cup 30 30
        echo "Press enter to return to main menu. "
        read;;
Q)

	clear 
		exit;;

q)
	clear
	        exit;;

*)
	echo "IMPROPER CHOICE"
	echo "Press Enter to continue"
	read id
esac
done

