#!/bin/bash
clear
while [ 1 ]
do
clear
echo
echo 
echo
tput cup 9 30
echo '--------------------------------------------------'
tput cup 10 30
echo '|  1. Create Users 	                       |'
tput cup 11 30
echo '|  2. Create Groups                              |'
tput cup 12 30
echo '|  3. Modify User                                |'
tput cup 13 30
echo '|  4. Change Password                            |'
tput cup 14 30
echo '|  Q. Quit                                       |'  
tput cup 15 30
echo '|  Enter your choice :                           |'
tput cup 16 30
echo '--------------------------------------------------'
tput cup 15 52 
read  choice
case $choice in
	
1) 	sh /netmin/rahul/system/user
	tput cup 30 30
	echo "Press enter to return to main menu. "
	read;;

2) 	sh /netmin/rahul/system/groups
	tput cup 30 30tput cup 30 30
	echo "Press enter to return to main menu. "
	read;;

3)      sh /netmin/rahul/system/moduser
        tput cup 30 30tput cup 30 30
        echo "Press enter to return to main menu. "
        read;;


4)      sh /netmin/rahul/system/chpass
        tput cup 30 30tput cup 30 30
        echo "Press enter to return to main menu. "
        read;;
Q)

	clear 
		exit;;

q)
	clear
	        exit;;

*)
	echo "IMPROPER CHOICE"
	echo "Press Enter to continue"
	read id
esac
done

