#!/bin/bash
clear
while [ 1 ]
do
clear
tput cup 4 20
echo -e "\33[33m ************************** \33[0m"
tput cup 5 20
echo -e "\33[37m  Welcome to Netmin Project \33[0m"
tput cup 6 20
echo -e "\33[32m ************************** \33[0m"
tput cup 7 20
echo '--------------------------------------------------'
tput cup 8 20
echo '|  1. Complete Hardware Information of your system|'
tput cup 9 20
echo '|  2. Detect New-Hardware on My System            |'
tput cup 10 20
echo '|  3. Check My Total  Memory Capacity             |'
tput cup 11 20
echo '|  4. Under Development                           |'
tput cup 12 20
echo '|  Q. Quit                                        |'
tput cup 13 20
echo -e "\33[45m|  Enter your choice:                             |\33[0m"
tput cup 14 20
echo '--------------------------------------------------'
tput cup 13 41
read  choice
case $choice in

1)      clear 
      tput cup 5 20  
echo -e "\33[42mInfo on Hardware Attached During the system Bootup \33[0m"
     cat /etc/sysconfig/hwconf |more
 tput cup 30 30
echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
tput cup 27 67 
        read;;

2)    clear  
    tput cup 5 20
echo -e "\33[42mRunning Kudzu To Detect My Newly Attached Hardware \33[0m"
tput cup 6 10
echo -e "\33[47mKudzu will Prompt you to configure if any new Hardware is found else simply exit\33[0m"
kudzu
tput cup 30 30
echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
tput cup 27 67 
       read;;

3)     clear
tput cup 5 20
echo -e "\33[45mCapacity Of Your Main Memory & Secondary Memory:In MBs \33[0m"
free -m  
tput cup 10 20
echo -e "\33[43m To Check In KB or GB Use command:free -k or -g\33[0m"
tput cup 30 30
echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
tput cup 27 67 
        read;;
4)      clear
echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
tput cup 27 67 
read;;

5)      clear
echo -e "\33[43m  Press Enter to Return to main Menu \33[0m"
        read ;;

Q)

        clear
                exit;;

q)
        clear
                exit;;

*)
echo -e "\33[35m  IMPROPER CHOICE \33[0m"
echo -e "\33[41m  Press Enter to Continue...! \33[0m"
 tput cup 30 42       
 read id
esac
done
