#!/bin/bash
user = 'whoami'
clear
if [ $user!=root ]
then 
	tput cup 9 30
	echo "You should have root privelege to run NETMIN"
	tput cup 10 30
	echo "Enter root PASSWORD"
	tput cup 11 30
	su - root -c "sh /netmin/rahul/menu"
	exit
fi
