#!/bin/bash
clear
tput cup 4 20
echo -e "\33[33m ************************** \33[0m"
tput cup 5 20
echo -e "\33[37m  Welcome to Netmin Project \33[0m"
tput cup 6 20
echo -e "\33[32m ************************** \33[0m"
tput cup 8 20
echo -e "\33[42m*************CRONJOB FOR ROOT*************\33[0m"


tput cup 12 20

crontab -l

tput cup 15 20
echo -e "\33[46mFor Other Users:crontab -u username -l\33[0m"


