#!/bin/bash
clear
tput cup 10 30
echo -n "Enter the name of the group:"
read group
if  `grep $group /etc/group >>/dev/null`
then
tput cup 11 30
echo "group already exixts "
tput cup 12 30
echo -n "press enter to return to main menu "
read
else
groupadd $group 2>/dev/null
tput cup 11 30
echo "Group successfully created"
tput cup 12 30
echo -n "Press enter to continue. "
read
fi
